# Generated by Django 3.2.8 on 2021-12-01 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trying2', '0002_rename_knowledgeable_details_all_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='startedfrom',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='started from'),
            preserve_default=False,
        ),
    ]
