# Generated by Django 3.2.8 on 2021-12-05 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trying2', '0003_lesson_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='tb',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='d2',
            field=models.BooleanField(default=False),
        ),
    ]
